name: broody
description: Your daily video diary app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+18

environment:
  sdk: ">=2.14.0 <3.0.0"

dependency_overrides:
  material_color_utilities: ^0.1.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5

  rxdart: ^0.27.5

  # State Management
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  state_notifier: ^0.7.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

  # UI
  google_fonts: ^3.0.1
  auto_route: ^5.0.4
  animations: ^2.0.3
  flutter_sticky_header:
    git:
      url: https://github.com/UnderKoen/flutter_sticky_header
  image_picker: 0.8.4+6
  path_provider: ^2.0.11
  implicitly_animated_reorderable_list: ^0.4.2
  duration: ^3.0.11
  video_player: ^2.4.5
  ffmpeg_kit_flutter_min_gpl: ^4.5.1
  photo_manager: ^2.5.2
  sliver_tools: ^0.2.7
  blur: ^3.1.0
  adaptive_dialog: ^1.7.0
  dartx: ^1.1.0
  flutter_blurhash: ^0.7.0
  blurhash_dart: ^1.1.0
  video_thumbnail: ^0.5.2
  blobs: ^2.0.0
  material_color_utilities: ^0.1.4
  share_plus: ^4.0.10
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  auto_size_text: ^3.0.0
  package_info: ^2.0.2
  wakelock: ^0.6.2
  loading_value: ^0.0.2
  broody_video: ^0.0.5-dev.1
  image_fade: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true

  image_path: "icons/icon.png"
  adaptive_icon_background: "#1A0E28"
  adaptive_icon_foreground: "icons/icon_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/
    - assets/rive/
    - assets/video/
    - fonts/
